# example config: https://gist.github.com/irfn/b869bab7a306a4eecb8a89d3610248c6

# XTerm's default colors
colors:
   # Default colors
   primary:
     background: '#000000'
     foreground: '#ffffff'
   # Normal colors
   normal:
     black:   '#000000'
     red:     '#c93333'
     green:   '#00c200'
     yellow:  '#c7c400'
     blue:    '#7777ee'
     magenta: '#c955c7'
     cyan:    '#44c5c7'
     white:   '#e5e5e5'

   # Bright colors
   bright:
     black:   '#7f7f7f'
     red:     '#ff0000'
     green:   '#00ff00'
     yellow:  '#ffff00'
     blue:    '#5c5cff'
     magenta: '#ff76ff'
     cyan:    '#00ffff'
     white:   '#ffffff'

# Font configuration
font:
    # The `style` can be specified to pick a specific face.
    # style: Regular
  normal:
    family: Monaco

  # Point size
  size: 11.5
